PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  	<http://www.w3.org/2002/07/owl#>
PREFIX xmlsn:  <http://xmlns.com/foaf/0.1/familyName>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX jolux: <http://data.legilux.lu/resource/ontology/jolux#>

select distinct ?property ?propertyType (group_concat(distinct ?superProperty ; separator = ", ") AS ?superProperties) ?inverse ?altLabel ?comment ?propertyAligned ?alignmentComment  ?scopeNote ?editorialNote
 
where
{
  {
	?property a owl:ObjectProperty.
    ?property a ?propertyType.
	OPTIONAL {
		?property rdfs:subPropertyOf ?superProperty. 
	}
	OPTIONAL {
		?property owl:inverseOf ?inverse. 
	}
	OPTIONAL {
    	?propertyAligned owl:equivalentProperty ?property.
	}
	OPTIONAL {
    	?property jolux:alignmentComment ?alignmentComment.
	}
	OPTIONAL {
		?inverse  owl:inverseOf ?property. 
	}
	OPTIONAL {
	?property skos:altLabel ?altLabel. 
	VALUES ?wantedLang {"fr" ''}.
	FILTER langMatches(lang(?altLabel), ?wantedLang)
	}
	OPTIONAL {
		?property rdfs:comment ?comment. 
		VALUES ?wantedLang {"fr" ''}.
		FILTER langMatches(lang(?comment), ?wantedLang)
	}
	OPTIONAL {
		?property skos:scopeNote ?scopeNote. 
	}
	OPTIONAL {
		?property skos:editorialNote ?editorialNote. 
	}
  } 
UNION
  {

	?property a owl:DatatypeProperty.
    ?property a ?propertyType.
	OPTIONAL {
		?property rdfs:subPropertyOf ?superProperty. 
	}
	OPTIONAL {
	?property skos:altLabel ?altLabel. 
	VALUES ?wantedLang {"fr" ''}.
	FILTER langMatches(lang(?altLabel), ?wantedLang)
	}
	OPTIONAL {
		?property rdfs:comment ?comment. 
		VALUES ?wantedLang {"en" ''}.
		FILTER langMatches(lang(?comment), ?wantedLang)
	}
	OPTIONAL {
    	?propertyAligned owl:equivalentProperty ?property.
	}
	OPTIONAL {
    	?property jolux:alignmentComment ?alignmentComment.
	}
	OPTIONAL {
		?property skos:scopeNote ?scopeNote. 
	}
	OPTIONAL {
		?property skos:editorialNote ?editorialNote. 
	}
  }
  UNION
  {

	?property a owl:DatatypeAnnotation.
    ?property a ?propertyType.
	OPTIONAL {
		?property rdfs:subPropertyOf ?superProperty. 
	}
	OPTIONAL {
		?property owl:inverseOf ?inverse. 
	}
	OPTIONAL {
		 ?inverse  owl:inverseOf ?property. 
	}
	OPTIONAL {
	?property skos:altLabel ?altLabel. 
	VALUES ?wantedLang {"fr" ''}.
	FILTER langMatches(lang(?altLabel), ?wantedLang)
	}
	OPTIONAL {
		?property rdfs:comment ?comment. 
		VALUES ?wantedLang {"en" ''}.
		FILTER langMatches(lang(?comment), ?wantedLang)
	}
	OPTIONAL {
		?property skos:scopeNote ?scopeNote. 
	}
	OPTIONAL {
		?property skos:editorialNote ?editorialNote. 
	}
  }
}  
GROUP BY ?property ?propertyType ?superProperties ?inverse ?altLabel ?comment ?propertyAligned ?alignmentComment ?scopeNote ?editorialNote
ORDER BY ?property


