#!/bin/bash
if ! [ -x "$(command -v arq)" ]; then
	echo 'Error: arq was not found, please make sure Jena is installed and you have added it to your path'>&2
	exit 1
fi

if ! [ -x "$(command -v python)" ]; then
	echo 'Error: python was not found, please make sure it is installed and you have added it to your path'>&2
	exit 1
fi

if [ ! -f "FormatCSV.py" ]; then
	echo 'Error: The python formatter was not found, please make sure it is in your current directory'>&2
	exit 1
fi

if ! [ $# -eq 3 ]; then
	echo 'ts-observe <ontology> <Observe-query.rq> <output.csv>'
	exit 1
fi

arq --data=$1 --query=$2 --results CSV > $3 && python FormatCSV.py $3
if [ $? -eq 0 ]; then
    echo "Observation successful! Check results in $3"
fi
