#!/usr/bin/env python
import os
import argparse
import FormatCSV

if __name__=="__main__":
	parser = argparse.ArgumentParser()
	parser.add_argument('-d','--dataset', nargs='+',
			required=True, type=argparse.FileType('r'), help='Ontologies to process')
	parser.add_argument('-q', '--query',  type=argparse.FileType('r'), required=True, help='Query to apply to the ontology')
	parser.add_argument('-f', '--format', nargs='?', default='CSV', help='The output format')
	parser.add_argument('-o', '--output',type=argparse.FileType('w'), required=True, help='Output file')
	args = parser.parse_args()
	# print(args)
	os.system("arq \"--dataset={{{0}}} --query={1} --results={2} > {3}\"".format(",".join([file.name for file in args.dataset]), args.query.name, args.format, args.output.name))
	if args.format.lower() == "csv":
		FormatCSV.formatFile(args.output.name)
